packages:
  - app/apex
  - app/jump
  - com/apex
  - com/core
  - com/jump
  - org/apex
  - org/core
  - org/jump
  - net/apex
  - net/jump

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.21
  vitest: npm:@voidzero-dev/vite-plus-test@^0.1.21

ignoredBuiltDependencies:
  - esbuild
  - sharp
  - workerd

minimumReleaseAge: 4320

minimumReleaseAgeExclude:
  - vite-plus
  - '@voidzero-dev/*'
  - oxlint
  - '@oxlint/*'
  - oxlint-tsgolint
  - '@oxlint-tsgolint/*'
  - oxfmt
  - '@oxfmt/*'
  - '@cloudflare/workers-types'

overrides:
  vite: 'catalog:'
  vitest: 'catalog:'

peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: '*'
    vitest: '*'
