/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PageRouteImport } from './routes/_page'
import { Route as HealthRouteImport } from './routes/health'
import { Route as ManifestDotwebmanifestRouteImport } from './routes/manifest[.]webmanifest'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as RevisionRouteImport } from './routes/revision'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PageIndexRouteImport } from './routes/_page.index'
import { Route as PageAboutRouteImport } from './routes/_page.about'
import { Route as PageDoctorRouteImport } from './routes/_page.doctor'
import { Route as PageExploreRouteImport } from './routes/_page.explore'
import { Route as PageHomeRouteImport } from './routes/_page.home'
import { Route as PageMessagesRouteImport } from './routes/_page.messages'
import { Route as PageNotificationsRouteImport } from './routes/_page.notifications'
import { Route as HealthLivenessesRouteImport } from './routes/health.livenesses'
import { Route as HealthReadinessesRouteImport } from './routes/health.readinesses'
import { Route as HealthStartupsRouteImport } from './routes/health.startups'
import { Route as PageConfigurationIndexRouteImport } from './routes/_page.configuration.index'
import { Route as PageConfigurationAccountRouteImport } from './routes/_page.configuration.account'
import { Route as ApiV0HealthDotjsonRouteImport } from './routes/api.v0.health[.]json'
import { Route as ApiV0RevisionDotjsonRouteImport } from './routes/api.v0.revision[.]json'

const PageRoute = PageRouteImport.update({
  id: '/_page',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ManifestDotwebmanifestRoute = ManifestDotwebmanifestRouteImport.update({
  id: '/manifest.webmanifest',
  path: '/manifest.webmanifest',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisionRoute = RevisionRouteImport.update({
  id: '/revision',
  path: '/revision',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PageIndexRoute = PageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PageRoute,
} as any)
const PageAboutRoute = PageAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PageRoute,
} as any)
const PageDoctorRoute = PageDoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => PageRoute,
} as any)
const PageExploreRoute = PageExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => PageRoute,
} as any)
const PageHomeRoute = PageHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => PageRoute,
} as any)
const PageMessagesRoute = PageMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PageRoute,
} as any)
const PageNotificationsRoute = PageNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PageRoute,
} as any)
const HealthLivenessesRoute = HealthLivenessesRouteImport.update({
  id: '/livenesses',
  path: '/livenesses',
  getParentRoute: () => HealthRoute,
} as any)
const HealthReadinessesRoute = HealthReadinessesRouteImport.update({
  id: '/readinesses',
  path: '/readinesses',
  getParentRoute: () => HealthRoute,
} as any)
const HealthStartupsRoute = HealthStartupsRouteImport.update({
  id: '/startups',
  path: '/startups',
  getParentRoute: () => HealthRoute,
} as any)
const PageConfigurationIndexRoute = PageConfigurationIndexRouteImport.update({
  id: '/configuration/',
  path: '/configuration/',
  getParentRoute: () => PageRoute,
} as any)
const PageConfigurationAccountRoute =
  PageConfigurationAccountRouteImport.update({
    id: '/configuration/account',
    path: '/configuration/account',
    getParentRoute: () => PageRoute,
  } as any)
const ApiV0HealthDotjsonRoute = ApiV0HealthDotjsonRouteImport.update({
  id: '/api/v0/health.json',
  path: '/api/v0/health.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiV0RevisionDotjsonRoute = ApiV0RevisionDotjsonRouteImport.update({
  id: '/api/v0/revision.json',
  path: '/api/v0/revision.json',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PageIndexRoute
  '/health': typeof HealthRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/offline': typeof OfflineRoute
  '/revision': typeof RevisionRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PageAboutRoute
  '/doctor': typeof PageDoctorRoute
  '/explore': typeof PageExploreRoute
  '/home': typeof PageHomeRoute
  '/messages': typeof PageMessagesRoute
  '/notifications': typeof PageNotificationsRoute
  '/health/livenesses': typeof HealthLivenessesRoute
  '/health/readinesses': typeof HealthReadinessesRoute
  '/health/startups': typeof HealthStartupsRoute
  '/configuration/account': typeof PageConfigurationAccountRoute
  '/api/v0/health.json': typeof ApiV0HealthDotjsonRoute
  '/api/v0/revision.json': typeof ApiV0RevisionDotjsonRoute
  '/configuration/': typeof PageConfigurationIndexRoute
}
export interface FileRoutesByTo {
  '/health': typeof HealthRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/offline': typeof OfflineRoute
  '/revision': typeof RevisionRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/about': typeof PageAboutRoute
  '/doctor': typeof PageDoctorRoute
  '/explore': typeof PageExploreRoute
  '/home': typeof PageHomeRoute
  '/messages': typeof PageMessagesRoute
  '/notifications': typeof PageNotificationsRoute
  '/health/livenesses': typeof HealthLivenessesRoute
  '/health/readinesses': typeof HealthReadinessesRoute
  '/health/startups': typeof HealthStartupsRoute
  '/': typeof PageIndexRoute
  '/configuration/account': typeof PageConfigurationAccountRoute
  '/api/v0/health.json': typeof ApiV0HealthDotjsonRoute
  '/api/v0/revision.json': typeof ApiV0RevisionDotjsonRoute
  '/configuration': typeof PageConfigurationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_page': typeof PageRouteWithChildren
  '/health': typeof HealthRouteWithChildren
  '/manifest.webmanifest': typeof ManifestDotwebmanifestRoute
  '/offline': typeof OfflineRoute
  '/revision': typeof RevisionRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_page/about': typeof PageAboutRoute
  '/_page/doctor': typeof PageDoctorRoute
  '/_page/explore': typeof PageExploreRoute
  '/_page/home': typeof PageHomeRoute
  '/_page/messages': typeof PageMessagesRoute
  '/_page/notifications': typeof PageNotificationsRoute
  '/health/livenesses': typeof HealthLivenessesRoute
  '/health/readinesses': typeof HealthReadinessesRoute
  '/health/startups': typeof HealthStartupsRoute
  '/_page/': typeof PageIndexRoute
  '/_page/configuration/account': typeof PageConfigurationAccountRoute
  '/api/v0/health.json': typeof ApiV0HealthDotjsonRoute
  '/api/v0/revision.json': typeof ApiV0RevisionDotjsonRoute
  '/_page/configuration/': typeof PageConfigurationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/manifest.webmanifest'
    | '/offline'
    | '/revision'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/doctor'
    | '/explore'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/health/livenesses'
    | '/health/readinesses'
    | '/health/startups'
    | '/configuration/account'
    | '/api/v0/health.json'
    | '/api/v0/revision.json'
    | '/configuration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/health'
    | '/manifest.webmanifest'
    | '/offline'
    | '/revision'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/about'
    | '/doctor'
    | '/explore'
    | '/home'
    | '/messages'
    | '/notifications'
    | '/health/livenesses'
    | '/health/readinesses'
    | '/health/startups'
    | '/'
    | '/configuration/account'
    | '/api/v0/health.json'
    | '/api/v0/revision.json'
    | '/configuration'
  id:
    | '__root__'
    | '/_page'
    | '/health'
    | '/manifest.webmanifest'
    | '/offline'
    | '/revision'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/_page/about'
    | '/_page/doctor'
    | '/_page/explore'
    | '/_page/home'
    | '/_page/messages'
    | '/_page/notifications'
    | '/health/livenesses'
    | '/health/readinesses'
    | '/health/startups'
    | '/_page/'
    | '/_page/configuration/account'
    | '/api/v0/health.json'
    | '/api/v0/revision.json'
    | '/_page/configuration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PageRoute: typeof PageRouteWithChildren
  HealthRoute: typeof HealthRouteWithChildren
  ManifestDotwebmanifestRoute: typeof ManifestDotwebmanifestRoute
  OfflineRoute: typeof OfflineRoute
  RevisionRoute: typeof RevisionRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiV0HealthDotjsonRoute: typeof ApiV0HealthDotjsonRoute
  ApiV0RevisionDotjsonRoute: typeof ApiV0RevisionDotjsonRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_page': {
      id: '/_page'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manifest.webmanifest': {
      id: '/manifest.webmanifest'
      path: '/manifest.webmanifest'
      fullPath: '/manifest.webmanifest'
      preLoaderRoute: typeof ManifestDotwebmanifestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revision': {
      id: '/revision'
      path: '/revision'
      fullPath: '/revision'
      preLoaderRoute: typeof RevisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/': {
      id: '/_page/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PageIndexRouteImport
      parentRoute: typeof PageRoute
    }
    '/_page/about': {
      id: '/_page/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PageAboutRouteImport
      parentRoute: typeof PageRoute
    }
    '/_page/doctor': {
      id: '/_page/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof PageDoctorRouteImport
      parentRoute: typeof PageRoute
    }
    '/_page/explore': {
      id: '/_page/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof PageExploreRouteImport
      parentRoute: typeof PageRoute
    }
    '/_page/home': {
      id: '/_page/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof PageHomeRouteImport
      parentRoute: typeof PageRoute
    }
    '/_page/messages': {
      id: '/_page/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof PageMessagesRouteImport
      parentRoute: typeof PageRoute
    }
    '/_page/notifications': {
      id: '/_page/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof PageNotificationsRouteImport
      parentRoute: typeof PageRoute
    }
    '/health/livenesses': {
      id: '/health/livenesses'
      path: '/livenesses'
      fullPath: '/health/livenesses'
      preLoaderRoute: typeof HealthLivenessesRouteImport
      parentRoute: typeof HealthRoute
    }
    '/health/readinesses': {
      id: '/health/readinesses'
      path: '/readinesses'
      fullPath: '/health/readinesses'
      preLoaderRoute: typeof HealthReadinessesRouteImport
      parentRoute: typeof HealthRoute
    }
    '/health/startups': {
      id: '/health/startups'
      path: '/startups'
      fullPath: '/health/startups'
      preLoaderRoute: typeof HealthStartupsRouteImport
      parentRoute: typeof HealthRoute
    }
    '/_page/configuration/': {
      id: '/_page/configuration/'
      path: '/configuration'
      fullPath: '/configuration/'
      preLoaderRoute: typeof PageConfigurationIndexRouteImport
      parentRoute: typeof PageRoute
    }
    '/_page/configuration/account': {
      id: '/_page/configuration/account'
      path: '/configuration/account'
      fullPath: '/configuration/account'
      preLoaderRoute: typeof PageConfigurationAccountRouteImport
      parentRoute: typeof PageRoute
    }
    '/api/v0/health.json': {
      id: '/api/v0/health.json'
      path: '/api/v0/health.json'
      fullPath: '/api/v0/health.json'
      preLoaderRoute: typeof ApiV0HealthDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/v0/revision.json': {
      id: '/api/v0/revision.json'
      path: '/api/v0/revision.json'
      fullPath: '/api/v0/revision.json'
      preLoaderRoute: typeof ApiV0RevisionDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PageRouteChildren {
  PageAboutRoute: typeof PageAboutRoute
  PageDoctorRoute: typeof PageDoctorRoute
  PageExploreRoute: typeof PageExploreRoute
  PageHomeRoute: typeof PageHomeRoute
  PageMessagesRoute: typeof PageMessagesRoute
  PageNotificationsRoute: typeof PageNotificationsRoute
  PageIndexRoute: typeof PageIndexRoute
  PageConfigurationAccountRoute: typeof PageConfigurationAccountRoute
  PageConfigurationIndexRoute: typeof PageConfigurationIndexRoute
}

const PageRouteChildren: PageRouteChildren = {
  PageAboutRoute: PageAboutRoute,
  PageDoctorRoute: PageDoctorRoute,
  PageExploreRoute: PageExploreRoute,
  PageHomeRoute: PageHomeRoute,
  PageMessagesRoute: PageMessagesRoute,
  PageNotificationsRoute: PageNotificationsRoute,
  PageIndexRoute: PageIndexRoute,
  PageConfigurationAccountRoute: PageConfigurationAccountRoute,
  PageConfigurationIndexRoute: PageConfigurationIndexRoute,
}

const PageRouteWithChildren = PageRoute._addFileChildren(PageRouteChildren)

interface HealthRouteChildren {
  HealthLivenessesRoute: typeof HealthLivenessesRoute
  HealthReadinessesRoute: typeof HealthReadinessesRoute
  HealthStartupsRoute: typeof HealthStartupsRoute
}

const HealthRouteChildren: HealthRouteChildren = {
  HealthLivenessesRoute: HealthLivenessesRoute,
  HealthReadinessesRoute: HealthReadinessesRoute,
  HealthStartupsRoute: HealthStartupsRoute,
}

const HealthRouteWithChildren =
  HealthRoute._addFileChildren(HealthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PageRoute: PageRouteWithChildren,
  HealthRoute: HealthRouteWithChildren,
  ManifestDotwebmanifestRoute: ManifestDotwebmanifestRoute,
  OfflineRoute: OfflineRoute,
  RevisionRoute: RevisionRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiV0HealthDotjsonRoute: ApiV0HealthDotjsonRoute,
  ApiV0RevisionDotjsonRoute: ApiV0RevisionDotjsonRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
