import type { Locale } from '../i18n';
import {
  about as enAbout,
  brand as enBrand,
  edit as enEdit,
  entries as enEntries,
  entriesdescription1 as enEntriesDescription,
  entriesempty1 as enEntriesEmpty,
  entriesheading1 as enEntriesHeading,
  entriespagetitle2 as enEntriesPageTitle,
  entriestitle1 as enEntriesTitle,
  entrybodystructured2 as enEntryBodyStructured,
  home as enHome,
  manage as enManage,
  next as enNext,
  pagination as enPagination,
  previous as enPrevious,
  primarynavlabel2 as enPrimaryNavLabel,
  publishedat1 as enPublishedAt,
  search as enSearch,
  searchdescription1 as enSearchDescription,
  searchheading1 as enSearchHeading,
  searchlabel1 as enSearchLabel,
  searchnoresults2 as enSearchNoResults,
  searchprompt1 as enSearchPrompt,
  searchresultcount2 as enSearchResultCount,
  searchsubmit1 as enSearchSubmit,
  searchtemporarynotice2 as enSearchTemporaryNotice,
  searchtitle1 as enSearchTitle,
  sitedocsabout02 as enSiteDocsAbout0,
  sitedocsabout12 as enSiteDocsAbout1,
  sitedocsdescription2 as enSiteDocsDescription,
  sitedocsheading2 as enSiteDocsHeading,
  sitedocsparagraph02 as enSiteDocsParagraph0,
  sitedocsproduct2 as enSiteDocsProduct,
  sitedocssitename3 as enSiteDocsSiteName,
  sitehelpabout02 as enSiteHelpAbout0,
  sitehelpabout12 as enSiteHelpAbout1,
  sitehelpdescription2 as enSiteHelpDescription,
  sitehelpheading2 as enSiteHelpHeading,
  sitehelpparagraph02 as enSiteHelpParagraph0,
  sitehelpproduct2 as enSiteHelpProduct,
  sitehelpsitename3 as enSiteHelpSiteName,
  siteinfoabout02 as enSiteInfoAbout0,
  siteinfoabout12 as enSiteInfoAbout1,
  siteinfodescription2 as enSiteInfoDescription,
  siteinfoheading2 as enSiteInfoHeading,
  siteinfoparagraph02 as enSiteInfoParagraph0,
  siteinfoproduct2 as enSiteInfoProduct,
  siteinfositename3 as enSiteInfoSiteName,
  sitenewsabout02 as enSiteNewsAbout0,
  sitenewsabout12 as enSiteNewsAbout1,
  sitenewsdescription2 as enSiteNewsDescription,
  sitenewsheading2 as enSiteNewsHeading,
  sitenewsparagraph02 as enSiteNewsParagraph0,
  sitenewsproduct2 as enSiteNewsProduct,
  sitenewssitename3 as enSiteNewsSiteName,
  skiptomain2 as enSkipToMain,
  unavailablebody1 as enUnavailableBody,
  unavailableheading1 as enUnavailableHeading,
  unavailabletitle1 as enUnavailableTitle,
  utilitynavlabel2 as enUtilityNavLabel,
  viewentries1 as enViewEntries,
} from '../paraglide/messages/en.js';
import {
  about as jaAbout,
  brand as jaBrand,
  edit as jaEdit,
  entries as jaEntries,
  entriesdescription1 as jaEntriesDescription,
  entriesempty1 as jaEntriesEmpty,
  entriesheading1 as jaEntriesHeading,
  entriespagetitle2 as jaEntriesPageTitle,
  entriestitle1 as jaEntriesTitle,
  entrybodystructured2 as jaEntryBodyStructured,
  home as jaHome,
  manage as jaManage,
  next as jaNext,
  pagination as jaPagination,
  previous as jaPrevious,
  primarynavlabel2 as jaPrimaryNavLabel,
  publishedat1 as jaPublishedAt,
  search as jaSearch,
  searchdescription1 as jaSearchDescription,
  searchheading1 as jaSearchHeading,
  searchlabel1 as jaSearchLabel,
  searchnoresults2 as jaSearchNoResults,
  searchprompt1 as jaSearchPrompt,
  searchresultcount2 as jaSearchResultCount,
  searchsubmit1 as jaSearchSubmit,
  searchtemporarynotice2 as jaSearchTemporaryNotice,
  searchtitle1 as jaSearchTitle,
  sitedocsabout02 as jaSiteDocsAbout0,
  sitedocsabout12 as jaSiteDocsAbout1,
  sitedocsdescription2 as jaSiteDocsDescription,
  sitedocsheading2 as jaSiteDocsHeading,
  sitedocsparagraph02 as jaSiteDocsParagraph0,
  sitedocsproduct2 as jaSiteDocsProduct,
  sitedocssitename3 as jaSiteDocsSiteName,
  sitehelpabout02 as jaSiteHelpAbout0,
  sitehelpabout12 as jaSiteHelpAbout1,
  sitehelpdescription2 as jaSiteHelpDescription,
  sitehelpheading2 as jaSiteHelpHeading,
  sitehelpparagraph02 as jaSiteHelpParagraph0,
  sitehelpproduct2 as jaSiteHelpProduct,
  sitehelpsitename3 as jaSiteHelpSiteName,
  siteinfoabout02 as jaSiteInfoAbout0,
  siteinfoabout12 as jaSiteInfoAbout1,
  siteinfodescription2 as jaSiteInfoDescription,
  siteinfoheading2 as jaSiteInfoHeading,
  siteinfoparagraph02 as jaSiteInfoParagraph0,
  siteinfoproduct2 as jaSiteInfoProduct,
  siteinfositename3 as jaSiteInfoSiteName,
  sitenewsabout02 as jaSiteNewsAbout0,
  sitenewsabout12 as jaSiteNewsAbout1,
  sitenewsdescription2 as jaSiteNewsDescription,
  sitenewsheading2 as jaSiteNewsHeading,
  sitenewsparagraph02 as jaSiteNewsParagraph0,
  sitenewsproduct2 as jaSiteNewsProduct,
  sitenewssitename3 as jaSiteNewsSiteName,
  skiptomain2 as jaSkipToMain,
  unavailablebody1 as jaUnavailableBody,
  unavailableheading1 as jaUnavailableHeading,
  unavailabletitle1 as jaUnavailableTitle,
  utilitynavlabel2 as jaUtilityNavLabel,
  viewentries1 as jaViewEntries,
} from '../paraglide/messages/ja.js';

/*
 * The generated locale modules contain plain message functions and do not
 * import Paraglide's browser/server strategy runtime. Named imports keep the
 * client bundle limited to messages used by this publishing cell; the
 * strategy runtime remains a server boundary.
 */
const EN = {
  about: enAbout,
  brand: enBrand,
  edit: enEdit,
  entries: enEntries,
  entriesdescription1: enEntriesDescription,
  entriesempty1: enEntriesEmpty,
  entriesheading1: enEntriesHeading,
  entriespagetitle2: enEntriesPageTitle,
  entriestitle1: enEntriesTitle,
  entrybodystructured2: enEntryBodyStructured,
  home: enHome,
  manage: enManage,
  next: enNext,
  pagination: enPagination,
  previous: enPrevious,
  primarynavlabel2: enPrimaryNavLabel,
  publishedat1: enPublishedAt,
  search: enSearch,
  searchdescription1: enSearchDescription,
  searchheading1: enSearchHeading,
  searchlabel1: enSearchLabel,
  searchnoresults2: enSearchNoResults,
  searchprompt1: enSearchPrompt,
  searchresultcount2: enSearchResultCount,
  searchsubmit1: enSearchSubmit,
  searchtemporarynotice2: enSearchTemporaryNotice,
  searchtitle1: enSearchTitle,
  sitedocsabout02: enSiteDocsAbout0,
  sitedocsabout12: enSiteDocsAbout1,
  sitedocsdescription2: enSiteDocsDescription,
  sitedocsheading2: enSiteDocsHeading,
  sitedocsparagraph02: enSiteDocsParagraph0,
  sitedocsproduct2: enSiteDocsProduct,
  sitedocssitename3: enSiteDocsSiteName,
  sitehelpabout02: enSiteHelpAbout0,
  sitehelpabout12: enSiteHelpAbout1,
  sitehelpdescription2: enSiteHelpDescription,
  sitehelpheading2: enSiteHelpHeading,
  sitehelpparagraph02: enSiteHelpParagraph0,
  sitehelpproduct2: enSiteHelpProduct,
  sitehelpsitename3: enSiteHelpSiteName,
  siteinfoabout02: enSiteInfoAbout0,
  siteinfoabout12: enSiteInfoAbout1,
  siteinfodescription2: enSiteInfoDescription,
  siteinfoheading2: enSiteInfoHeading,
  siteinfoparagraph02: enSiteInfoParagraph0,
  siteinfoproduct2: enSiteInfoProduct,
  siteinfositename3: enSiteInfoSiteName,
  sitenewsabout02: enSiteNewsAbout0,
  sitenewsabout12: enSiteNewsAbout1,
  sitenewsdescription2: enSiteNewsDescription,
  sitenewsheading2: enSiteNewsHeading,
  sitenewsparagraph02: enSiteNewsParagraph0,
  sitenewsproduct2: enSiteNewsProduct,
  sitenewssitename3: enSiteNewsSiteName,
  skiptomain2: enSkipToMain,
  unavailablebody1: enUnavailableBody,
  unavailableheading1: enUnavailableHeading,
  unavailabletitle1: enUnavailableTitle,
  utilitynavlabel2: enUtilityNavLabel,
  viewentries1: enViewEntries,
} as const;

const JA = {
  about: jaAbout,
  brand: jaBrand,
  edit: jaEdit,
  entries: jaEntries,
  entriesdescription1: jaEntriesDescription,
  entriesempty1: jaEntriesEmpty,
  entriesheading1: jaEntriesHeading,
  entriespagetitle2: jaEntriesPageTitle,
  entriestitle1: jaEntriesTitle,
  entrybodystructured2: jaEntryBodyStructured,
  home: jaHome,
  manage: jaManage,
  next: jaNext,
  pagination: jaPagination,
  previous: jaPrevious,
  primarynavlabel2: jaPrimaryNavLabel,
  publishedat1: jaPublishedAt,
  search: jaSearch,
  searchdescription1: jaSearchDescription,
  searchheading1: jaSearchHeading,
  searchlabel1: jaSearchLabel,
  searchnoresults2: jaSearchNoResults,
  searchprompt1: jaSearchPrompt,
  searchresultcount2: jaSearchResultCount,
  searchsubmit1: jaSearchSubmit,
  searchtemporarynotice2: jaSearchTemporaryNotice,
  searchtitle1: jaSearchTitle,
  sitedocsabout02: jaSiteDocsAbout0,
  sitedocsabout12: jaSiteDocsAbout1,
  sitedocsdescription2: jaSiteDocsDescription,
  sitedocsheading2: jaSiteDocsHeading,
  sitedocsparagraph02: jaSiteDocsParagraph0,
  sitedocsproduct2: jaSiteDocsProduct,
  sitedocssitename3: jaSiteDocsSiteName,
  sitehelpabout02: jaSiteHelpAbout0,
  sitehelpabout12: jaSiteHelpAbout1,
  sitehelpdescription2: jaSiteHelpDescription,
  sitehelpheading2: jaSiteHelpHeading,
  sitehelpparagraph02: jaSiteHelpParagraph0,
  sitehelpproduct2: jaSiteHelpProduct,
  sitehelpsitename3: jaSiteHelpSiteName,
  siteinfoabout02: jaSiteInfoAbout0,
  siteinfoabout12: jaSiteInfoAbout1,
  siteinfodescription2: jaSiteInfoDescription,
  siteinfoheading2: jaSiteInfoHeading,
  siteinfoparagraph02: jaSiteInfoParagraph0,
  siteinfoproduct2: jaSiteInfoProduct,
  siteinfositename3: jaSiteInfoSiteName,
  sitenewsabout02: jaSiteNewsAbout0,
  sitenewsabout12: jaSiteNewsAbout1,
  sitenewsdescription2: jaSiteNewsDescription,
  sitenewsheading2: jaSiteNewsHeading,
  sitenewsparagraph02: jaSiteNewsParagraph0,
  sitenewsproduct2: jaSiteNewsProduct,
  sitenewssitename3: jaSiteNewsSiteName,
  skiptomain2: jaSkipToMain,
  unavailablebody1: jaUnavailableBody,
  unavailableheading1: jaUnavailableHeading,
  unavailabletitle1: jaUnavailableTitle,
  utilitynavlabel2: jaUtilityNavLabel,
  viewentries1: jaViewEntries,
} as const;

export type MessageCatalog = typeof JA;

export function messagesFor(locale: Locale): MessageCatalog {
  return locale === 'en' ? EN : JA;
}
