import { fileURLToPath } from 'node:url';

// Vitest configuration for ONE deployment unit.
//
// Deliberately self-contained: it extends nothing at the repository root, so
// this directory stays runnable if it is ever extracted into its own
// repository. The mocks under test/__mocks__ are this unit's own copies —
// per CLAUDE.md, duplication across frames is intentional, so that one frame's
// test requirements never force a change in another frame.
import { defineConfig } from 'vitest/config';

export default defineConfig({
  oxc: {
    jsx: {
      runtime: 'automatic',
    },
  },
  resolve: {
    alias: {
      // Only workerd resolves `cloudflare:workers`. `src/lib/cloudflare-env.ts`
      // is the one importer, so one alias covers the whole unit.
      'cloudflare:workers': fileURLToPath(
        new URL('./test/__mocks__/cloudflare-workers.ts', import.meta.url),
      ),
      // A zero-cost marker module in the real build; in Node it is a bare
      // specifier Vitest cannot resolve.
      '@tanstack/react-start/server-only': fileURLToPath(
        new URL('./test/__mocks__/server-only.ts', import.meta.url),
      ),
    },
    tsconfigPaths: true,
  },
  test: {
    coverage: {
      exclude: [
        '**/+types/**',
        '**/*.d.ts',
        '**/*.test.{ts,tsx}',
        '**/node_modules/**',
        '**/build/**',
        '**/dist/**',
        '**/__mocks__/**',
        '**/public/**',
        '**/*.css',
        '**/*.svg',
        '**/locales/**',
        '**/coverage/**',
        '**/.wrangler/**',
        '**/e2e/**',
        '**/playwright.config.ts',
        '**/vite.config.ts',
        '**/vitest.config.ts',
        '**/vitest.setup.ts',
        // Generated by the TanStack Router plugin from the files in `src/routes`.
        'src/routeTree.gen.ts',
        // Wiring only: it builds the TanStack request handler, which exists in
        // the Worker build and nowhere else, so no Node test can import it. The
        // nonce mint and header wrap live in `src/lib/app-request.ts` and are
        // covered there. `src/router.tsx` is deliberately NOT excluded: the
        // tests drive a real router through it.
        'src/lib/app-handler.ts',
        // Worker-only ALS install: `node:async_hooks` must not enter the client
        // graph. The default store in `security-nonce.ts` is what Vitest drives.
        'src/security-nonce-als.ts',
      ],
      include: ['src/**/*.{ts,tsx,js,jsx}'],
      provider: 'v8',
      reporter: ['text', 'text-summary'],
      thresholds: {
        branches: 100,
        functions: 100,
        lines: 100,
        statements: 100,
      },
    },
    deps: {
      interopDefault: true,
    },
    environment: 'happy-dom',
    globals: true,
    include: ['test/**/*.test.{ts,tsx}'],
    setupFiles: ['./vitest.setup.ts'],
  },
});
